name: Conda install

on:
  push:
    branches: [master]
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment/REQreate_environment.yml
          activate-environment: reqreate
          auto-activate-base: false

      - name: The command exists
        run: reqreate --version
